### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by insolor** [insolor/zig-collections#3]
- [ ] Add docs in the code
- [ ] Implement `Counter.mostCommon` using [heap sort](https://en.wikipedia.org/wiki/Heapsort)
- [ ] Split `Counter` into common `Counter` and `StringCounter`
